### ISSUE TITLE
RangeError (index): Invalid value: Valid value range is empty: 0

### ISSUE THREAD

**Issue by syedzain1** [devdreamsolution/flutter-fitness-app#2]
**Describe the bug**

**To Reproduce**
1. After Signup
2. Click on NASCAR
3. Click on "Start Workout"
4. Click on "I'm ready!"
5. After count down reaches to 1.
6. I get this error on both iOS and Android. Error is "RangeError (index): Invalid value: Valid value range is empty: 0"

**Expected behavior**
It should start exercise but it shows error

**Screenshots**
here is the screenshot.
![image](https://user-images.githubusercontent.com/72284378/95028839-cd205a80-06bc-11eb-89f2-52274f3eabbe.png)
![Screen Shot 2020-10-05 at 3 34 51 AM](https://user-images.githubusercontent.com/72284378/95028842-d5789580-06bc-11eb-8434-dd6e48a3d25a.png)

**Smartphone (please complete the following information):**
Device: [11 Pro Max]
OS: [iOS13.3]

**Additional context**

**Comment by Sophie627** [comment]
Hello, This is old code.
I update firestore database structure.
Please check new code.
https://github.com/Sophie627/flutter-fitness

**Comment by devdreamsolution** [comment]
Thank you @Sophie627 
And @syedzain1 I hope this gives you some helping.
Thank you to use our open source.
